const SORT_BY_PRICE_LOW_TO_HIGH = 0
const SORT_BY_PRICE_HIGH_TO_LOW = 1
const SORT_BY_AVERAGE_RATING = 2
const SORT_BY_REVIEW_COUNT = 3

module.exports = {
  SORT_BY_PRICE_LOW_TO_HIGH,
  SORT_BY_PRICE_HIGH_TO_LOW,
  SORT_BY_AVERAGE_RATING,
  SORT_BY_REVIEW_COUNT
}
